test_size: 0.2
batch_size: 32
n_workers: 4
n_epochs: 60

model: "xception"
pretrained: True
scheduler: "ReduceLROnPlateau"
optimizer: "Adam"
label_smoothing: 
lr: 0.00001
img_size: 224
patience: 7
dropout: 
momentum: 
gamma: 
step_size: 