vectors_dir: 'data/vectors/'
rasters_dir: 'data/rasters/'
columns: ['UID', 'source', 'iso', 'country', 'region', 'subregion', 'name', 'geometry', 'giga_id_school']

iso_codes: [
    'SEN', 'ATG', 'AIA', 'BWA', 'MDG', 'BEN', 'BIH', 'BLZ', 'BRB', 'CRI', 
    'DMA', 'GHA', 'GIN', 'GRD', 'HND', 'HUN', 'KAZ', 'KEN', 'KIR', 'KNA', 
    'LCA', 'MNG', 'MSR', 'MWI', 'NAM', 'NER', 'NGA', 'PAN', 'RWA', 'SLE', 
    'SLV', 'SSD', 'THA', 'TTO', 'UKR', 'UZB', 'VCT', 'VGB', 'ZAF', 'ZWE', 
    'BRA'
]

proximity: 50
filter_buffer_size: 150
sample_spacing: 300
object_proximity: 300
name_match_threshold: 85
name_match_proximity: 300
priority: ["OSM", "OVERTURE", "UNICEF"]

school: {
    amenity: [
        "school",
        "academy"
    ],
    translated: [
        "مدرسة",
        "مدرسة",
        "أكاديمية",
        "akadimiya",
        "shule",
        "akademia",
        "makaranta",
        "ile-iwe",
        "ile-iwe giga",
        "akademi",
        "isikole",
        "ትምህርት ቤት",
        "iskuul",
        "skool",
        "akademie",
        "école",
        "académie",
        "escuela",
        "escola",
        "мектеп",
        "am-pianarana",
        "maktab",
        "škola",
        "школа",
        "iskola",
        "сургууль",
        "ishuri",
        "โรงเรียน",
        "chikoro",
        "isikolo"
    ]
}
non_school: {
    amenity: [
        "fast_food",
        "food_court",
        "cafe",
        "restaurant",
        "pub",
        "bar",
        "bank",
        "clinic",
        "doctors",
        "hospital",
        "pharmacy",
        "dentist",
        "veterinary",
        "arts_centre",
        "cinema",
        "casino",
        "community_centre",
        "conference_centre",
        "events_venue",
        "fuel",
        "exhibition_centre",
        "planetarium",
        "theatre",
        "nightclub",
        "courthouse",
        "fire_station",
        "police",
        "post_office",
        "prison",
        "townhall",
        "crematorium",
        "funeral_hall",
        "internet_cafe",
        "marketplace",
        "place_of_mourning",
        "place_of_worship"
    ],
    building: [
        "commercial",
        "industrial",
        "office",
        "retail",
        "warehouse",
        "church",
        "cathedral",
        "chapel",
        "mosque",
        "temple",
        "synagogue",
        "shrine",
        "supermarket",
        "fire_station",
        "police",
        "prison",
        "hospital",
        "museum",
        "military"
    ],
    craft: [
        "agricultural_engines",
        "atelier",
        "bakery",
        "blacksmith",
        "boatbuilder",
        "brewery",
        "cabinet_maker",
        "carpenter",
        "electronics_repair",
        "distillery",
        "oil_mill"
    ],
    healthcare: [
        "alternative",
        "audiologist",
        "birthing_center",
        "chiropractor",
        "dentist",
        "midwife",
        "occupational_therapist",
        "optometrist",
        "physiotherapist",
        "psychologist",
        "speech_therapist",
        "blood_bank",
        "blood_donation",
        "vaccination_centre"
    ],
    historic: [
        "church",
        "cathedral",
        "castle",
        "mosque",
        "tower"
    ],
    landuse: [
        "commercial",
        "retail",
        "industrial",
        "warehouse",
        "cemetery",
        "religious"
    ],
    leisure: [
        "adult_gaming_centre",
        "amusement_arcade"
    ],
    military: [
        "barracks",
        "base",
        "office"
    ],
    place: [
        "farm",
        "allotments"
    ],
    power: [
        "transformer"
    ],
    public_transport: [
        "station"
    ],
    railway: [
        "station"
    ],
    office: [
        "government"
    ],
    shop: [
        "alcohol",
        "bakery",
        "beverages",
        "brewing_supplies",
        "butcher",
        "cheese",
        "chocolate",
        "coffee",
        "confectionery",
        "convenience",
        "farm",
        "food",
        "general",
        "department_store",
        "kiosk",
        "mall",
        "supermarket",
        "wholesale",
        "beauty",
        "fabric",
        "fashion",
        "doityourself",
        "electronics",
        "garden_centre"
    ],
    tourism: [
        "guest_house",
        "hostel",
        "hotel",
        "motel",
        "museum",
        "chalet",
        "apartment",
        "zoo"
    ]
}

exclude: 
- "Pre"
- "Pre-school"
- "Preschool"
- "Kinder"
- "Kindergarten"
- "Infant"
- "Baby"
- "Daycare"
- "Nursery"
- "Swim"
- "Swimming"
- "Sports"
- "Fitness"
- "Taekwando"
- "Dance"
- "Soccer"
- "Bikeride"
- "Basketball"
- "Taekwondo"
- "Football"
- "Tennis"
- "Ballet"
- "Martial Arts"
- "Combat"
- "Driving"
- "Flight"
- "Aviation"
- "K9"
- "Dog"
- "Sunday School"
- "Quick Minds"
- "Beauty"
- "Cosmetics"
- "Makeup"
- "Salon"
- "Art"
- "Nails"
- "Tattoo"
- "Music"
- "Startup"
- "Coding"
- "Code"
- "Museum"
- "Business"
- "Management"
- "Medicine"
- "Medical"
- "Nursing"
- "Professional"
- "Professionnelle"
- "Language"
- "English"
- "Bookstore"
- "Supplies"
- "Tutor"
- "Tutors"
- "University"
- "College"
- "Yunivesithi"
- "جامعة"
- "كلية"
- "رياضة"
- "Chuo kikuu"
- "Chuo"
- "Koleji"
- "ዩኒቨርሲቲ"
- "Yuniversiti"
- "Universiteit"
- "Kollege"
- "Université"
- "Collège"
- "Collége"
- "Technical"
- "Institute"
- "Institut"
- "Institution"